# Generated by Django 3.2.10 on 2021-12-09 09:06

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=20)),
                ('authors', djongo.models.fields.JSONField()),
                ('number_of_pages', models.IntegerField()),
                ('publisher', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
